### ISSUE TITLE
Document how to deploy webapp

### ISSUE THREAD

**Issue by ruiwanguk** [PRIDE-Cluster/cluster-web-app#27]
It would be nice to document in README.md on how to deploy the webapp.

**Comment by jadianes** [comment]
I'm not sure what do we need to document here. Right now the code is structures as a Java container based webapp, so there isn't much to document since it depends on what you use. For tomcat we build the war file and then copy to the deploy folder. As you know the steps depends pretty much on our particular Tomcat configuration. Ideally in the future we will remove the Tomcat "dependency" from the code base since there isn't a reason for it apart form us using Tomcat as a web application server. This is because I didn't document anything here. It will be very generic, dependent on our particular EBI use case, and in any case it will be simple instructions about how to build and deploy a war file.

**Comment by ruiwanguk** [comment]
Thx Jose, I tried the deploy the webapp the other day, as I mentioned before, my build is much smaller than your original build, so I stopped since I don't know whether this is correct or not. 

I will try to deploy the webapp alone, if I run into problems, will give you a shout.

**Comment by jadianes** [comment]
In case somebody runs into the same issue, it could be that before "waring" the file, be need to follow the npm/bower building process as documented, in order to get all the dependencies. But this needs to be tested yet.

**Comment by ruiwanguk** [comment]
It already documentated
